### ISSUE TITLE
Not sending invitation email

### ISSUE THREAD

**Issue by tubia** [ipedrazas/taiga-docker#13]
Hi,
I'm trying to make taiga.io sends invitation emails. Actually, the `local.py` is correctly configured, as reported in the docs. I'll copy here the part for email configuration:
```
# MAIL OPTIONS
DEFAULT_FROM_EMAIL = "taiga@myhost.io"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.myhost.io"
EMAIL_HOST_USER = "taiga@myhost.io"
EMAIL_HOST_PASSWORD = "XXX"
EMAIL_PORT = 587
```
Checking the logs using `docker logs taiga-back` It reports all the attempts to send emails (without reporting an error) displaying the whole email in the log. Checking a single email in the log I found that the invitation link reports the wrong url:

> Hi,
> you have been invited to the project 'RebAl'.
> If you want to join to this project go to http://taiga-front:9001/invitation/alfanumericcode for accept > this invitation.

Anyone managed to solve this?

**Comment by ipedrazas** [comment]
I think it would be better to post this in the Taiga repo... I have no knowledge of the internals of Taiga, I'm afraid :)
