### ISSUE TITLE
Django backend - missing static files

### ISSUE THREAD

**Issue by umens** [ipedrazas/taiga-docker#14]
Hello.

I successfully install everythings but the css/img/... of the Django interface (admin) is missing because of the wrong URL.

![image](https://cloud.githubusercontent.com/assets/765858/8954293/e1d39838-35e4-11e5-8c26-ba46e08751d6.png)

I used a public domain name for the install and i think this is why.

In docker-settings.py of taiga-back : (lines 193-200)

```python
# The absolute url is mandatory because attachments
# urls depends on it. On production should be set
# something like https://media.taiga.io/
MEDIA_URL = "http://localhost:8000/media/"

# Static url is not widelly used by taiga (only
# if admin is activated).
STATIC_URL = "http://localhost:8000/static/"
```

I don't know how to change it because i just begin to use docker. Is there a way of doing it manually ?

Or maybe the following command can handle this.
```bash
export API_NAME=boot2docker"
```

sorry for my english. 

and thanks for your great job ! :+1:

**Comment by ipedrazas** [comment]
Well spotted!!

Let me run some tests

**Comment by ipedrazas** [comment]
It's fixed. make sure to remove the old images/containers and re-run `setup.sh`

**Comment by umens** [comment]
Works like a charm ! thx for the quick fix :+1:
