### ISSUE TITLE
Building custom domain taiga

### ISSUE THREAD

**Issue by vernak2539** [ipedrazas/taiga-docker#2]
after running the following

`docker run -it --rm --link postgres:postgres taiga/taiga-back bash regenerate.sh`

I get the message below. Any idea what would be causing this?

```bash
Unable to find image 'taiga/taiga-back' locally
Pulling repository taiga/taiga-back
2014/11/17 08:53:04 Error: image taiga/taiga-back not found
```

**Comment by ipedrazas** [comment]
Taiga just released a new version of the frontend that it's built. Closing this issue since it doesn't apply anymore.
