### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by codentest** [ipedrazas/taiga-docker#20]
First Thank you for your work to make Taiga dockerized.

I followed the instructions and then went to the http://<hostip>/ and used admin/123123 as username password and I get a bad username/password error.

I then attempted to reset password for "admin", and it says that user is not registered.

I looked in the database and users_user table has the user admin with id = 4 and active=true.
But I don't see any rows inside the users_authdata and users_role tables.

I'm not sure if the database setup is incomplete for the user to login or what else is wrong.

Are you able to login to your test runs?

**Comment by hanu18** [comment]
First check browser console for exact error. That will help every to get more details.
If you are using this image locally then use  API_NAME="10.10.10.10", i.e. IP of your server.

**Comment by dalareo** [comment]
The same here. I could reproduce error with other docker scripts like https://github.com/htdvisser/taiga-docker or https://github.com/benhutchins/docker-taiga. Could it be a bug/failure in Taiga.io new versions??

**Comment by rtorino** [comment]
@dalareo We have the same issue. I also commented on this issue https://github.com/taigaio/taiga-front/issues/415 my findings of what is probably causing the issue.

**Comment by lshengjian** [comment]
We have the same issue.

**Comment by dalareo** [comment]
Checkout this:

https://github.com/taigaio/taiga-doc/blob/master/setup-production.adoc

You have to populate the database with initial basic data

**Comment by ipedrazas** [comment]
closing
