### ISSUE TITLE
e-mail Configuration

### ISSUE THREAD

**Issue by hanu18** [ipedrazas/taiga-docker#21]
Hi 
please anyone help me to configure email with this image.
When i m trying to add new user, it is not sending any request to newly created user.

**Comment by tubia** [comment]
This thing is still a problem that in fact prevents to use this image productively.

**Comment by hanu18** [comment]
Then please suggest any alternate way to do the same.....
or any better working image with steps....
Thanks :)

**Comment by cgonzalezg** [comment]
```shell
docker run -d --name taiga-back  -v "$(pwd)"/backend/docker-settings.py:/taiga/settings/local.py:ro -p 8000:8000 --link postgres:postgres ipedrazas/taiga-back
```
then you can change the configuration in the file backend/docker-settings.py
```py
# MAIL OPTIONS
DEFAULT_FROM_EMAIL = "john@doe.com"
#By default is using the console
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'user@gmail.com'
EMAIL_HOST_PASSWORD = 'supersecret'

DJMAIL_REAL_BACKEND = "django.core.mail.backends.console.EmailBackend"
```

**Comment by ipedrazas** [comment]
closing
