### ISSUE TITLE
Deployment on AWS

### ISSUE THREAD

**Issue by pyvandenbussche** [ipedrazas/taiga-docker#22]
Hi, thanks for the great work. You say there is something special to be done if we want to deploy on AWS (cf. http://ivan.pedrazas.me/2014/10/08/local-taiga-with-docker/). Can you elaborate more? At the moment if I deploy the 3 containers using your setup.sh, there seems to be a problem with the API communication between front/back and therefore I can not login. Can you add such information on the readme?

Thanks a lot!

**Comment by ipedrazas** [comment]
I think the login is for a different reason but the main problem now is that we're updating the containers to Taiga 1.9 and there are some issues to be fixed :)

To use it in AWS or any other place really, you will need to define the DNS for the API host. In the docs this ` export API_NAME=boot2docker` tells the frontend how to resolve the backend.

I guess that in your case the first thing would be to create a DNS entry for that machine, for example:

taiga.mydomain.com

And then to add ` export API_NAME=taiga.mydomain.com`

Does it make sense?

**Comment by pyvandenbussche** [comment]
Thanks for the answer. What I had in mind was to not expose the APIs publicly. Thus using the default localhost API_NAME but it seems not to be working fine ...

**Comment by ipedrazas** [comment]
It's the client who needs access to the API. By client I mean the browser... so, I'm not sure how you're going to do that.

You can have a nginx as proxy in front of the API, but the API has to be accessible by the javascript running on the client.

**Comment by pyvandenbussche** [comment]
Makes sense! Thank you
