### ISSUE TITLE
Call to Taiga git repo seem to be updated!

### ISSUE THREAD

**Issue by mehany** [ipedrazas/taiga-docker#3]
Hi.. when i run   docker run -it --rm --link postgres:postgres taiga/taiga-back bash regenerate.sh    i get     Pulling repository taiga/taiga-back
2015/01/06 02:17:40 HTTP code: 404

**Comment by Thieum** [comment]
Should taiga/taiga-back be replaced by ipedrazas/taiga-back ? This one seems to be registered in the hub.

**Comment by mehany** [comment]
Closing this, Docker scripts has been updated so this issue does not apply any more!
