### ISSUE TITLE
Create User disabled

### ISSUE THREAD

**Issue by pomelo** [ipedrazas/taiga-docker#40]
I installed Taiga through setup.sh, exported API_NAME=192.168.1.200. 
I can log in using the admin account, but cannot register any user account. I didn't see any admin pages for user administration either. 

Here is the output of http://192.168.1.200:8000/api/v1/invitations
`GET /api/v1/invitations
HTTP 403 FORBIDDEN
Vary: Accept
Allow: GET, HEAD, OPTIONS
Content-Type: application/json

{
    "_error_type": "taiga.base.exceptions.PermissionDenied",
    "_error_message": "You don't have permisions to see that."
}`

**Comment by hitokiri** [comment]
you changue url to /admin/
