### ISSUE TITLE
Add info on what to do on first run

### ISSUE THREAD

**Issue by magthe** [ipedrazas/taiga-docker#6]
Just to simplify things for the newcomer (me) add something like this to the README:

> Once you've successfully run `run-taiga.sh` start a web browser and point it to `http://localhost:80`.  You should be greeted by a login page.  The administrators username is *admin*, and the password is *123123*.

**Comment by ipedrazas** [comment]
You could have created a PR... but thanks, I'm adding it now :)

**Comment by ipedrazas** [comment]
added!
