### ISSUE TITLE
Simplify setup by using fig.sh or docker-compose

### ISSUE THREAD

**Issue by rtorino** [ipedrazas/taiga-docker#7]

**Comment by lgersman** [comment]
:+1:

**Comment by ipedrazas** [comment]
Compose... it is coming :)

**Comment by chrisamoore** [comment]
Compose status ?

**Comment by prologic** [comment]
btw just tried to spin this up based on your current state of the repo and it failed with some progres errors; don't have time to really look in to it right now; just maknig a note here :)

**Comment by ipedrazas** [comment]
Moved to Kubernetes. closing this issue.
