### ISSUE TITLE
Some error when running setup.sh

### ISSUE THREAD

**Issue by diegoaguilar** [ipedrazas/taiga-docker#8]
I ran the command but got some python error related to unicode decoding somewhere.

This is my log output
https://gist.github.com/diegoaguilar/a12eb4df24a581a9bd37

**Comment by brecke** [comment]
I get the same error...

**Comment by janmejay4150** [comment]
I am also getting the same error. Any resolution?

**Comment by ipedrazas** [comment]
Finally, this has been fixed :)
